from PyInquirer import Separator

standard_regions=[
    {
        'name':'us-east-1(N. Virginia)',
        'disabled':False,
        'value':'us-east-1'
    },
    {
        'name':'us-east-2(Ohio)',
        'disabled':False,
        'value':'us-east-2'
    },
    {
        'name':'us-west-1(N. California)',
        'disabled':False,
        'value':'us-west-1'
    },
    {
        'name':'us-west-2(Oregon)',
        'disabled':False,
        'value':'us-west-2'
    },
    {
        'name':'ap-south-1(Mumbai)',
        'disabled':False,
        'value':'ap-south-1'
    },
    {
        'name':'ap-northeast-1(Tokyo)',
        'disabled':False,
        'value':'ap-northeast-1'
    },
    {
        'name':'ap-northeast-2(Seoul)',
        'disabled':False,
        'value':'ap-northeast-2'
    },
    {
        'name':'ap-northeast-3(Osaka)',
        'disabled':False,
        'value':'ap-northeast-3'
    },
    {
        'name':'ap-southeast-1(Singapore)',
        'disabled':False,
        'value':'ap-southeast-1'
    },
    {
        'name':'ap-southeast-2(Sydney)',
        'disabled':False,
        'value':'ap-southeast-2'
    },
    {
        'name':'ca-central-1(Central)',
        'disabled':False,
        'value':'ca-central-1'
    },
    {
        'name':'eu-west-1(Ireland)',
        'disabled':False,
        'value':'eu-west-1'
    },
    {
        'name':'eu-west-2(London)',
        'disabled':False,
        'value':'eu-west-2'
    },
    {
        'name':'eu-west-3(Paris)',
        'disabled':False,
        'value':'eu-west-3'
    },
    {
        'name':'eu-central-1(Frankfurt)',
        'disabled':False,
        'value':'eu-central-1'
    },
    {
        'name':'eu-north-1(Stockholm)',
        'disabled':False,
        'value':'eu-north-1'
    },
    {
        'name':'sa-east-1(São Paulo)',
        'disabled':False,
        'value':'sa-east-1'
    },
    Separator(),
    {
        'name':'Opt-in/GovCloud/China Regions',
        'disabled':False,
        'value':False
    }
    ]

other_regions=[
    {
        'name':'af-south-1(Cape Town)',
        'value':"af-south-1",
        'disabled':False
    },
    {
        'name':'ap-east-1(Hong Kong)',
        'value':"ap-east-1",
        'disabled':False
    },
    {
        'name':'ap-southeast-3(Jakarta)',
        'value':"ap-southeast-3",
        'disabled':False
    },
    {
        'name':'eu-south-1(Milan)',
        'value':"eu-south-1",
        'disabled':False
    },
    {
        'name':'me-south-1(Bahrain)',
        'value':"me-south-1",
        'disabled':False
    },
    {
        'name':'us-gov-west-1(US-West)',
        'value':"us-gov-west-1",
        'disabled':"unsupported"
    },
    {
        'name':'us-gov-east-1(US-East)',
        'value':"us-gov-east-1",
        'disabled':"unsupported"
    },
    {
        'name':'cn-north-1(Beijing)',
        'value':"cn-north-1",
        'disabled':"unsupported"
    }, 
    {
        'name':'cn-northwest-1(Ningxia)',
        'value':"cn-northwest-1",
        'disabled':"unsupported"
    }
]