name: Code Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  trufflehog-credentials-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1

  bandit-security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit scan
      run: bandit -r . -lll --confidence high --severity high

  safety-dependency-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0
  
    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Install Safety
      run: pip install safety
  
    - name: Run Safety Check
      run: safety check --full-report

  pylint-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0
    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.7
    - name: Install Pylint
      run: pip install pylint
    - name: Run Pylint
      run: pylint **/*.py